---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  reek:
    enabled: true
  rubocop:
    enabled: true
ratings:
   paths:
   - "**.rb"
   - "lib/**/*.rb"
exclude_paths:
  - exmaples/*
  - test/*