---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  reek:
    enabled: true
    checks:
      ControlCouple/BooleanParameter:
        enabled: false
  rubocop:
    enabled: true
ratings:
   paths:
   - "**.rb"
   - "lib/**/*.rb"
exclude_paths:
  - examples/*
  - test/*