language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode # JRuby in 1.9 mode
  - ruby-head
  - jruby-head
  - rbx-19mode
  - 1.8.7
  - ree
  - jruby-18mode
env:
- COVERALLS=true
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: 1.8.7
    - rvm: rbx-18mode
    - rvm: rbx-19mode
    - rvm: jruby-18mode
    - rvm: ree
