language: ruby
before_install: gem install bundler
rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.6
  - 2.1.10
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
addons:
  code_climate:
    repo_token: 23033d2cdd6fc716e197d5d02ef14de39f4ebc79db6d13808aefd1b48b545b0a
